### ISSUE TITLE
Weird Error and I don't know how to describe it

### ISSUE THREAD

**Issue by un1tycyb3r** [g0ldencybersec/gungnir#1]
Love the tool. Weird error this morning while running it.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7c6bfc]

goroutine 758 [running]:
main.scanLog({0x944710, 0xc53ce0}, {0xc0000ac1a0, 0x1c}, 0xd952e6c0e0891067?, 0xe1acea4db374cd93?)
        /root/go/pkg/mod/github.com/g0ldencybersec/gungnir@v1.0.2/gungnir/main.go:233 +0x8dc
created by main.main in goroutine 1
        /root/go/pkg/mod/github.com/g0ldencybersec/gungnir@v1.0.2/gungnir/main.go:277 +0x1d0

**Comment by un1tycyb3r** [comment]
Fixed with updated version
